name: Push a release to Maven Central

on:
    push:
        tags:
            - '4.*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            MAVEN_DEPLOY_USERNAME: ${{ secrets.MAVEN_DEPLOY_USERNAME }}
            MAVEN_DEPLOY_TOKEN: ${{ secrets.MAVEN_DEPLOY_TOKEN }}
            MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
            - name: Java setup
              uses: actions/setup-java@v4
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: maven
                  server-id: 'oss.sonatype'
                  server-username: 'MAVEN_DEPLOY_USERNAME'
                  server-password: 'MAVEN_DEPLOY_TOKEN'
                  gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
                  gpg-passphrase: 'MAVEN_GPG_PASSPHRASE'
            - name: Install just
              uses: taiki-e/install-action@just
            - name: Deploy to Maven Central
              run: just deploy-to-maven-central
